spring.config.activate.on-profile: default
server.port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: databas
    password: databas
    url: jdbc:postgresql://localhost:5432/localdb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql : true
---

spring.config.activate.on-profile: docker
server.port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: databas
    password: databas
    url: jdbc:postgresql://tidig-dev_tidig-db_1:5432/localdb
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: postgresql
---

