version: "3.9"
services:
  tidig-server:
     build: tidig-dev-server
     mem_limit: 350m
     environment:
        - SPRING_PROFILES_ACTIVE=docker
     ports:
        - "8080:8080"
     depends_on:
        tidig-db:
            condition: service_healthy
  tidig-db:
     build: tidig-dev-db
     environment:
        - POSTGRES_PASSWORD=postgres
     ports:
        - "5432:5432"
     healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 10
